---
- name: Look up paperless user
  ansible.builtin.getent:
    database: passwd
    key: "{{ paperless_user }}"

- name: Set paperless uid/gid facts
  ansible.builtin.set_fact:
    paperless_uid: "{{ ansible_facts['getent_passwd'][paperless_user][1] }}"
    paperless_gid: "{{ ansible_facts['getent_passwd'][paperless_user][2] }}"

- name: Create Paperless directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: svc-paperless
    group: "{{ item.group }}"
    mode: "0750"
  loop:
    - { path: "{{ paperless_data_dir }}", group: svc-paperless }
    - { path: "{{ paperless_data_dir }}/consume", group: docs-rw }
    - { path: "{{ paperless_data_dir }}/consume/double-sided", group: docs-rw }

- name: Deploy Paperless docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ paperless_data_dir }}/docker-compose.yml"
    mode: "0600"
  no_log: true
  notify: Restart paperless

- name: Start Paperless
  community.docker.docker_compose_v2:
    project_src: "{{ paperless_data_dir }}"
    state: present
