---
- name: Configure mail server (Postfix + Dovecot + OpenDKIM)
  hosts: mail
  become: true

  roles:
    - role: mail-base
      tags: mail-base
    - role: mail-sshd
      tags: mail-sshd
    - role: mail-users
      tags: mail-users
    - role: mail-certbot
      tags: mail-certbot
    - role: mail-postfix
      tags: mail-postfix
    - role: mail-dovecot
      tags: mail-dovecot
    - role: mail-opendkim
      tags: mail-opendkim
    - role: mail-spamassassin
      tags: mail-spamassassin
    - role: mail-roundcube
      tags: mail-roundcube
    - role: mail-nginx
      tags: mail-nginx
    - role: mail-fail2ban
      tags: mail-fail2ban
    - role: mail-agent
      tags: mail-agent
