---
- name: Look up navidrome user
  ansible.builtin.getent:
    database: passwd
    key: "{{ navidrome_user }}"

- name: Set navidrome uid/gid facts
  ansible.builtin.set_fact:
    navidrome_uid: "{{ ansible_facts['getent_passwd'][navidrome_user][1] }}"
    navidrome_gid: "{{ ansible_facts['getent_passwd'][navidrome_user][2] }}"

- name: Create Navidrome directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ navidrome_user }}"
    mode: "0755"
  loop:
    - "{{ navidrome_data_dir }}"
    - "{{ navidrome_data_dir }}/data"
    - "{{ navidrome_data_dir }}/cache"

- name: Deploy Navidrome docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ navidrome_data_dir }}/docker-compose.yml"
    owner: "{{ navidrome_user }}"
    mode: "0644"
  notify: Restart navidrome

- name: Start Navidrome
  community.docker.docker_compose_v2:
    project_src: "{{ navidrome_data_dir }}"
    state: present
