---
audiobookshelf_version: "2.33.1"
audiobookshelf_port: 13378
audiobookshelf_data_dir: /opt/audiobookshelf
audiobookshelf_media_dir: /srv/media/audiobooks
audiobookshelf_podcasts_dir: /srv/media/podcasts
audiobookshelf_user: svc-media
