---
- name: Look up audiobookshelf user
  ansible.builtin.getent:
    database: passwd
    key: "{{ audiobookshelf_user }}"

- name: Set audiobookshelf uid/gid facts
  ansible.builtin.set_fact:
    audiobookshelf_uid: "{{ ansible_facts['getent_passwd'][audiobookshelf_user][1] }}"
    audiobookshelf_gid: "{{ ansible_facts['getent_passwd'][audiobookshelf_user][2] }}"

- name: Create Audiobookshelf directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ audiobookshelf_user }}"
    mode: "0755"
  loop:
    - "{{ audiobookshelf_data_dir }}"
    - "{{ audiobookshelf_data_dir }}/config"
    - "{{ audiobookshelf_data_dir }}/metadata"

- name: Deploy Audiobookshelf docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ audiobookshelf_data_dir }}/docker-compose.yml"
    owner: "{{ audiobookshelf_user }}"
    mode: "0644"
  notify: Restart audiobookshelf

- name: Start Audiobookshelf
  community.docker.docker_compose_v2:
    project_src: "{{ audiobookshelf_data_dir }}"
    state: present
